### ISSUE TITLE
Early development 

### ISSUE THREAD

**Issue by harikt** [cadrephp/Cadre.Module#1]
Hi Andrew Shell, 

I was excited to see your module for I like Aura.Di more than any other Di.

One suggestion for all your projects is why not release 0.x versions first than 1.x versions?

It helps to get early feedback and not run out of api changes or issues.

Just a suggestion.

Thank you and this is a great way :+1:  .

**Comment by andrewshell** [comment]
Good idea! Now the main branch is 0.x and the first tagged version is 0.1.0.

Packagist only listed one download which was mine so I figured it was safe.

**Comment by harikt** [comment]
Good to hear. And thanks for making it so quick.

**Comment by andrewshell** [comment]
It was pretty easy.  Now the main branch is 0.x and the first tagged
version is 0.1.0.

Packagist only listed one download which was me so I figured it was
safe.

Cheers,
Andrew

On Thu, Oct 20, 2016, at 12:28 PM, Andrew Shell wrote:

> Thanks, Hari! Not a bad idea.  I wonder if I can change it to 0.1.0
> now and not break packagist.
> 
> On Thu, Oct 20, 2016, at 11:58 AM, Hari K T wrote:
> 
> > Hi Andrew Shell,
> > I was excited to see your module for I like Aura.Di more than any
> > other Di.
> > One suggestion for all your projects is why not release 0.x versions
> > first than 1.x versions?
> > It helps to get early feedback and not run out of api changes or
> > issues.
> > Just a suggestion.
> > Thank you and this is a great way 👍  .
> > — You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub[1], or mute the
> > thread[2].

Links:
1. https://github.com/cadrephp/Cadre.Module/issues/1

**Comment by andrewshell** [comment]
Thanks, Hari! Not a bad idea.  I wonder if I can change it to 0.1.0 now
and not break packagist.

On Thu, Oct 20, 2016, at 11:58 AM, Hari K T wrote:

> Hi Andrew Shell,
> I was excited to see your module for I like Aura.Di more than any
> other Di.
> One suggestion for all your projects is why not release 0.x versions
> first than 1.x versions?
> It helps to get early feedback and not run out of api changes
> or issues.
> Just a suggestion.
> Thank you and this is a great way 👍  .
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:
1. https://github.com/cadrephp/Cadre.Module/issues/1
